### ISSUE TITLE
Any plans on creating an AUR package?

### ISSUE THREAD

**Issue by Ghibranalj** [ArthurSonzogni/rgb-tui#1]
If you don't, i'll be more than happy to make one for you.

**Comment by Ghibranalj** [comment]
i made one for you without your permission (blame it on my ADD).
https://aur.archlinux.org/packages/rgb-tui-git/

PS. if you want to maintain it i will transfer it to you

**Comment by ArthurSonzogni** [comment]
You are awesome. Thanks!

I added a link to your AUR package:
https://github.com/ArthurSonzogni/rgb-tui/commit/730b9082b01ae9917134ec421589ed0ec81cdf09

I think I would prefer to let you maintain this PKGBUILD. Just one question: could you compile in release mode? `cmake -DCMAKE_BUILD_TYPE=Release .`

**Comment by Ghibranalj** [comment]
> could you compile in release mode? `cmake -DCMAKE_BUILD_TYPE=Release` .


Aye aye captain

**Comment by Ghibranalj** [comment]
Could you name the tar files properly as in `rgb-tui-1.1.0-Linux.tar.gz` instead of `rgb-tui-1.0.0-Linux.tar.gz` for v1.1 so that i can package the binary as well?

##### Edit :
I managed to do it anyway 
https://aur.archlinux.org/packages/rgb-tui-bin/
but it would definitely be much easier to maintain if the tar file is properly named

**Comment by ArthurSonzogni** [comment]
> > could you compile in release mode? `cmake -DCMAKE_BUILD_TYPE=Release` .
> 
> Aye aye captain

;-) Thank you!



> Could you name the tar files properly as in `rgb-tui-1.1.0-Linux.tar.gz` instead of `rgb-tui-1.0.0-Linux.tar.gz` for v1.1 so that i can package the binary as well?
> 
> ##### Edit :
> I managed to do it anyway https://aur.archlinux.org/packages/rgb-tui-bin/ but it would definitely be much easier to maintain if the tar file is properly named

This is the name chosen by cmake. There are probably ways to customize it, but I don't know immediately. I can try if you want, but since you managed to find ways to go without it, it might not worth it.

---

Thank you so much for all the work you did for package `rgb-tui` for AUR!

**Comment by Ghibranalj** [comment]
You're welcome!.
`yay -S rgb-tui` works now.
it will now let you choose between git version and binary version.
You might wanna add that to the readme!
