### ISSUE TITLE
Phony numbers?

### ISSUE THREAD

**Issue by ardnew** [ArthurSonzogni/rgb-tui#4]
So, great tool, nearly perfect in every way. I say _nearly_ because of one small curiosity: the hexadecimal digits alphabet goes from `0—G`... which is `17` different symbols. That is, you are using **_heptadecimal_** digits instead of **_hexadecimal_**!

What really blew my mind is that as you slide one of the component `R`, `G`, or `B` sliders around, you'll see the decimal `R,G,B` triplets correctly range from `0—255=16²`, while the hex values range from `#00—#GG` (or `0—289=17²`)). Thus, there must be at least `34` hex values pairs that both correspond to the **same** decimal number in each RGB component!

**Comment by ArthurSonzogni** [comment]
Welcome!
That's an interesting bug ;-)
Thanks for reporting this!

**Comment by ArthurSonzogni** [comment]
Thanks for the fix!
