### ISSUE TITLE
App building but not working on PowerPC: GUI is “frozen”

### ISSUE THREAD

**Issue by barracuda156** [ArthurSonzogni/rgb-tui#6]
@ArthurSonzogni I built the same app (v. 1.1) on Sonoma aarch64 and Snow Leopard ppc, and in the latter case GUI is unresponsive (static, as on the screenshot below). There are no crashes or errors displayed.

Any idea what can I try to have it fixed?

![rgb-tui](https://github.com/ArthurSonzogni/rgb-tui/assets/92015510/5046bff9-8e28-4f7c-a88b-59b8467cb7d0)

**Comment by ArthurSonzogni** [comment]
I upgraded FTXUI version:
Could you please check if this improves something?

Does GDB reports a stack trace when trying to interrupt it?

**Comment by barracuda156** [comment]
@ArthurSonzogni Turned out I somewhat mischaracterized the situation. GUI is not dead, it is just not responding to clicks on it (as it does on Sonoma). From keyboard I was able to move sliders, and colors change. Does not look overly usable still due to how colors are displayed, but it is not broken, as I thought initially.

![rgb2](https://github.com/ArthurSonzogni/rgb-tui/assets/92015510/3b12d636-7b1b-4165-9bae-db27e54da9ca)

**Comment by barracuda156** [comment]
P. S. I actually used FTXUI lib which we have it MacPorts: https://github.com/macports/macports-ports/blob/cf2aa331b84e43ab897c546f2e1896d13cb4c668/graphics/rgb-tui/Portfile

Could you make a new release of FTXUI, maybe v. 5.0.1? MacPorts folks do not like commit-based versions, especially when the port already used a release.

**Comment by ArthurSonzogni** [comment]
The terminal should advertise itself as supporting 256 colors, otherwise, FTXUI will fallback toward the "closest" color available.

This can be done with:
```sh
export TERM=xterm-256color
```
or
```sh
export COLORTERM=truecolor
```

Does this appears to be good enough for you?
I can also "force" FTXUI to output the true colors, but users of incompatible terminal will see some black colors instead of the fallback ones.

> Could you make a new release of FTXUI, maybe v. 5.0.1? MacPorts folks do not like commit-based versions, especially when the port already used a release.

The next version will be 6.0.0. I would like to avoid introducing a new breaking release too often.
Why do you need a new version in MadcPorts?

**Comment by barracuda156** [comment]
@ArthurSonzogni If 5.0.0 is good enough for all apps which use it, no need to introduce anything. I just thought that update you mentioned implied an update to FTXUI itself.

Env variables should be good, perhaps rather not force any specific setting for all users. I will try setting colors once back to the PowerMac.

Support for mouse events is something SDK-related, so it won’t work on earlier OS? No big deal, just to confirm.

**Comment by barracuda156** [comment]
@ArthurSonzogni Setting either of env variables makes it looks really strange for me :) 

This is with truecolor:
![rgb-tui_truecolor](https://github.com/ArthurSonzogni/rgb-tui/assets/92015510/a06555f9-51b5-46b8-bb4e-8b071b1e6668)

**Comment by ArthurSonzogni** [comment]
Your terminal probably doesn't support true colors. That's why it doesn't set those variable. That's why FTXUi fallback toward the "closest" supported colors.

Does it make sense?

**Comment by barracuda156** [comment]
> Your terminal probably doesn't support true colors. That's why it doesn't set those variable. That's why FTXUi fallback toward the "closest" supported colors.
> 
> Does it make sense?

Oh okay, looks like Apple Terminal had no true color up to very recently (or maybe still does not have it): https://stackoverflow.com/questions/6403744/are-there-terminals-that-support-true-color
Then no surprise, indeed.

I will look for some feasible alternative, I want to see how it works at least.

**Comment by barracuda156** [comment]
@ArthurSonzogni I can confirm it works in `vte`:

![rgb-tui_vte](https://github.com/ArthurSonzogni/rgb-tui/assets/92015510/e35e2a50-6ddb-4efc-acc7-028ae68285b9)

Sorry for the false alarm, there is no problem on `rgb-tui` side at all.
